language: php

sudo: true

services:
  - mysql

addons:
  firefox: "47.0.1"
  postgresql: "9.5"
  apt:
    packages:
    - openjdk-8-jre

cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/.npm

php:
 - 7.2

env:
  - DB=pgsql  MOODLE_BRANCH=MOODLE_36_STABLE NODEJS=8
  - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE NODEJS=8
  - DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
  - DB=pgsql  MOODLE_BRANCH=MOODLE_39_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE

matrix:
  include:
    - php: 5.6
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_33_STABLE NODEJS=8
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE NODEJS=8
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=master

before_install:
  - export MOODLE_VERSION=$(echo "$MOODLE_BRANCH" | cut -d'_' -f 2)
  - phpenv config-rm xdebug.ini
  - if [ "$NODEJS" = 8 ]; then
      nvm install 8.9;
      nvm use 8.9;
    else
      nvm install 14.0.0;
      nvm use 14.0.0;
    fi
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
 - moodle-plugin-ci phplint
 - moodle-plugin-ci phpcpd
 - moodle-plugin-ci phpmd
 - moodle-plugin-ci codechecker
 - moodle-plugin-ci validate
 - moodle-plugin-ci savepoints
 - moodle-plugin-ci mustache
 - moodle-plugin-ci grunt
 - moodle-plugin-ci phpunit
# Behat tests are failing due to issue:
# https://github.com/blackboard-open-source/moodle-plugin-ci/issues/70
# Commenting it out until the issue is fixed.
# - moodle-plugin-ci behat
