name: Run all tests for Moodle 39+

on: [push, pull_request]

jobs:
  workflow_group_39_plus_ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/group-39-plus-ci.yml@main
    with:
      disable_behat: true
